const base = '/assets/illustrations';

export const stillAssets = {
  cats: {
    sleeping: `${base}/cats/cat_sleeping.png`,
    sitting: `${base}/cats/cat_sitting.png`,
    stretching: `${base}/cats/cat_stretching.png`,
    gingerSleepingCurled: `${base}/cats/cat_ginger_sleeping_curled.png`,
    gingerLoafSleeping: `${base}/cats/cat_ginger_loaf_sleeping.png`,
    gingerRestingAwake: `${base}/cats/cat_ginger_resting_awake.png`,
    gingerSitting: `${base}/cats/cat_ginger_sitting.png`,
    gingerStandingCurious: `${base}/cats/cat_ginger_standing_curious.png`,
    gingerStandingSmiling: `${base}/cats/cat_ginger_standing_smiling.png`,
    gingerWalking: `${base}/cats/cat_ginger_walking.png`,
    gingerGrooming: `${base}/cats/cat_ginger_grooming_paw.png`,
    gingerPlayBow: `${base}/cats/cat_ginger_play_bow.png`,
    gingerStretching: `${base}/cats/cat_ginger_stretching.png`,
  },
  dogs: {
    puppySleeping: `${base}/dogs/puppy_sleeping.png`,
    puppySitting: `${base}/dogs/puppy_sitting.png`,
    puppyStanding: `${base}/dogs/puppy_standing.png`,
    goldenSleeping: `${base}/dogs/golden_sleeping.png`,
    goldenSitting: `${base}/dogs/golden_sitting.png`,
    goldenStanding: `${base}/dogs/golden_standing.png`,
    goldenWalking: `${base}/dogs/golden_walking.png`,
    shipomSitting: `${base}/dogs/shipom_sitting.png`,
    shipomSittingHappy: `${base}/dogs/shipom_sitting_happy.png`,
    shipomSittingOneEarUp: `${base}/dogs/shipom_sitting_one_ear_up.png`,
    shipomStandingFront: `${base}/dogs/shipom_standing_front.png`,
    shipomStandingSide: `${base}/dogs/shipom_standing_side.png`,
    shipomWalking: `${base}/dogs/shipom_walking.png`,
    shipomRestingSphinx: `${base}/dogs/shipom_resting_sphinx.png`,
    shipomRestingFlat: `${base}/dogs/shipom_resting_flat.png`,
    shipomRestingCurled: `${base}/dogs/shipom_resting_curled.png`,
    shipomLyingRelaxed: `${base}/dogs/shipom_lying_relaxed.png`,
    aspinSitting: `${base}/dogs/aspin_sitting.png`,
    aspinStandingHappy: `${base}/dogs/aspin_standing_happy.png`,
    aspinCurious: `${base}/dogs/aspin_curious.png`,
    aspinPlayingBall: `${base}/dogs/aspin_playing_with_ball.png`,
    aspinPlayingStick: `${base}/dogs/aspin_playing_with_stick.png`,
    aspinPlayingStickBlanket: `${base}/dogs/aspin_playing_with_stick_and_blanket.png`,
    aspinCuddlingPair: `${base}/dogs/aspin_cuddling_pair.png`,
    aspinFoodBowl: `${base}/dogs/aspin_sitting_with_food_bowl.png`,
    aspinSleepingBed: `${base}/dogs/aspin_sleeping_on_bed.png`,
    aspinSleepingRoundBed: `${base}/dogs/aspin_sleeping_on_round_bed.png`,
  },
  mood: {
    calm: `${base}/mood-energy/mood_calm.png`,
    sad: `${base}/mood-energy/mood_sad.png`,
    overwhelmed: `${base}/mood-energy/mood_overwhelmed.png`,
    loved: `${base}/mood-energy/mood_loved.png`,
  },
  energy: {
    tired: `${base}/mood-energy/energy_tired.png`,
    resting: `${base}/mood-energy/energy_resting.png`,
    motivated: `${base}/mood-energy/energy_motivated.png`,
  },
  weather: {
    partlySunny: `${base}/weather/weather_partly_sunny.png`,
    cloudy: `${base}/weather/weather_cloudy.png`,
    overcast: `${base}/weather/weather_overcast.png`,
    rain: `${base}/weather/weather_rain.png`,
    thunderstorm: `${base}/weather/weather_thunderstorm.png`,
    windy: `${base}/weather/weather_windy.png`,
    rainbow: `${base}/weather/weather_rainbow.png`,
    snow: `${base}/weather/weather_snow.png`,
    fog: `${base}/weather/weather_fog.png`,
    tornado: `${base}/weather/weather_tornado.png`,
  },
  time: {
    dawn: `${base}/time/time_dawn_peeking_sun.png`,
    sunrise: `${base}/time/time_sunrise_soft_hills.png`,
    morning: `${base}/time/time_morning_clear_sky.png`,
    midday: `${base}/time/time_midday_bright_sun.png`,
    earlyEvening: `${base}/time/time_early_evening_sun.png`,
    goldenHour: `${base}/time/time_golden_hour.png`,
    sunset: `${base}/time/time_sunset_pink_sky.png`,
    twilight: `${base}/time/time_twilight.png`,
    night: `${base}/time/time_night_crescent_moon.png`,
    deepNight: `${base}/time/time_deep_night_stars.png`,
  },
  sky: {
    cloud: `${base}/sky/sky_cloud_fluffy.png`,
    sun: `${base}/sky/sky_sun_smiling.png`,
    moon: `${base}/sky/sky_moon_with_stars.png`,
    sparkles: `${base}/sky/sky_sparkle_stars.png`,
    rainbow: `${base}/sky/sky_rainbow_clouds.png`,
    wind: `${base}/sky/sky_wind_swirl_pastel.png`,
    shootingStar: `${base}/sky/sky_shooting_star_pastel.png`,
    sunCloud: `${base}/sky/sky_sun_behind_cloud.png`,
    sleepingCloudMoon: `${base}/sky/sky_sleeping_cloud_moon.png`,
    stars: `${base}/sky/sky_star_cluster_pastel.png`,
  },
  plants: {
    leafy: `${base}/plants/plant_leafy.png`,
    fern: `${base}/plants/plant_fern.png`,
    hangingVine: `${base}/plants/plant_hanging_vine.png`,
    lavender: `${base}/plants/plant_lavender.png`,
    peaceLily: `${base}/plants/plant_peace_lily.png`,
    pinkFlowers: `${base}/plants/plant_pink_flowers.png`,
    pinkBlossoms: `${base}/plants/plant_pink_blossoms_blush_pot.png`,
    succulent: `${base}/plants/plant_succulent_cluster.png`,
    tallDracaena: `${base}/plants/plant_tall_dracaena.png`,
    tallLeaves: `${base}/plants/plant_tall_leaves.png`,
    yellowBlossoms: `${base}/plants/plant_yellow_blossoms.png`,
  },
  nature: {
    flowers: `${base}/nature/nature_flower_cluster_pastel.png`,
    leaves: `${base}/nature/nature_leaf_pair.png`,
    butterflies: `${base}/nature/nature_butterflies_pastel_pair.png`,
    bee: `${base}/nature/nature_bee_sparkle.png`,
    dandelion: `${base}/nature/nature_dandelion_wish.png`,
    mushroom: `${base}/nature/nature_mushroom_red_spotted.png`,
    dragonfly: `${base}/nature/nature_dragonfly_blue.png`,
    flowerPot: `${base}/nature/nature_flower_pot_pastel.png`,
    acorns: `${base}/nature/nature_acorns_pair.png`,
    woodland: `${base}/nature/nature_rocks_log_flowers.png`,
  },
  cozy: {
    tea: `${base}/cozy/tea_cup_saucer.png`,
    coffee: `${base}/cozy/coffee_mug.png`,
    books: `${base}/cozy/stacked_books.png`,
    candle: `${base}/cozy/heart_jar_candle.png`,
    window: `${base}/cozy/cozy_window.png`,
    blanket: `${base}/cozy/folded_blanket.png`,
    pillow: `${base}/cozy/cat_pillow.png`,
    wateringCan: `${base}/cozy/watering_can.png`,
    rug: `${base}/cozy/round_woven_rug.png`,
  },
  celebrations: {
    newYearFireworks: `${base}/celebrations/new_year_fireworks.png`,
    newYearStars: `${base}/celebrations/new_year_star_cluster.png`,
    newYearBanner: `${base}/celebrations/new_year_banner.png`,
    valentinesHearts: `${base}/celebrations/valentines_heart_cluster.png`,
    valentinesFlowers: `${base}/celebrations/valentines_flower_bouquet.png`,
    valentinesLetter: `${base}/celebrations/valentines_love_letter.png`,
    halloweenPumpkin: `${base}/celebrations/halloween_friendly_pumpkin.png`,
    halloweenMoon: `${base}/celebrations/halloween_crescent_moon.png`,
    halloweenGhost: `${base}/celebrations/halloween_friendly_ghost.png`,
    easterEgg: `${base}/celebrations/easter_decorated_egg.png`,
  },
} as const;

export type StillAssetPath = string;
