const base = `${import.meta.env.BASE_URL}assets/illustrations`;

export const stillAssets = {
  cats: {
    sleeping: `${base}/cats/cat_sleeping.webp`,
    sitting: `${base}/cats/cat_sitting.webp`,
    stretching: `${base}/cats/cat_stretching.webp`,
    gingerSleepingCurled: `${base}/cats/cat_ginger_sleeping_curled.webp`,
    gingerLoafSleeping: `${base}/cats/cat_ginger_loaf_sleeping.webp`,
    gingerRestingAwake: `${base}/cats/cat_ginger_resting_awake.webp`,
    gingerSitting: `${base}/cats/cat_ginger_sitting.webp`,
    gingerStandingCurious: `${base}/cats/cat_ginger_standing_curious.webp`,
    gingerStandingSmiling: `${base}/cats/cat_ginger_standing_smiling.webp`,
    gingerWalking: `${base}/cats/cat_ginger_walking.webp`,
    gingerGrooming: `${base}/cats/cat_ginger_grooming_paw.webp`,
    gingerPlayBow: `${base}/cats/cat_ginger_play_bow.webp`,
    gingerStretching: `${base}/cats/cat_ginger_stretching.webp`,
  },
  dogs: {
    puppySleeping: `${base}/dogs/puppy_sleeping.webp`,
    puppySitting: `${base}/dogs/puppy_sitting.webp`,
    puppyStanding: `${base}/dogs/puppy_standing.webp`,
    goldenSleeping: `${base}/dogs/golden_sleeping.webp`,
    goldenSitting: `${base}/dogs/golden_sitting.webp`,
    goldenStanding: `${base}/dogs/golden_standing.webp`,
    goldenWalking: `${base}/dogs/golden_walking.webp`,
    shipomSitting: `${base}/dogs/shipom_sitting.webp`,
    shipomSittingHappy: `${base}/dogs/shipom_sitting_happy.webp`,
    shipomSittingOneEarUp: `${base}/dogs/shipom_sitting_one_ear_up.webp`,
    shipomStandingFront: `${base}/dogs/shipom_standing_front.webp`,
    shipomStandingSide: `${base}/dogs/shipom_standing_side.webp`,
    shipomWalking: `${base}/dogs/shipom_walking.webp`,
    shipomRestingSphinx: `${base}/dogs/shipom_resting_sphinx.webp`,
    shipomRestingFlat: `${base}/dogs/shipom_resting_flat.webp`,
    shipomRestingCurled: `${base}/dogs/shipom_resting_curled.webp`,
    shipomLyingRelaxed: `${base}/dogs/shipom_lying_relaxed.webp`,
    aspinSitting: `${base}/dogs/aspin_sitting.webp`,
    aspinStandingHappy: `${base}/dogs/aspin_standing_happy.webp`,
    aspinCurious: `${base}/dogs/aspin_curious.webp`,
    aspinPlayingBall: `${base}/dogs/aspin_playing_with_ball.webp`,
    aspinPlayingStick: `${base}/dogs/aspin_playing_with_stick.webp`,
    aspinPlayingStickBlanket: `${base}/dogs/aspin_playing_with_stick_and_blanket.webp`,
    aspinCuddlingPair: `${base}/dogs/aspin_cuddling_pair.webp`,
    aspinFoodBowl: `${base}/dogs/aspin_sitting_with_food_bowl.webp`,
    aspinSleepingBed: `${base}/dogs/aspin_sleeping_on_bed.webp`,
    aspinSleepingRoundBed: `${base}/dogs/aspin_sleeping_on_round_bed.webp`,
  },
  checkIn: {
    mood: {
      sad: `${base}/check-ins/mood/mood-01-sad.webp`,
      calm: `${base}/check-ins/mood/mood-02-calm.webp`,
      content: `${base}/check-ins/mood/mood-03-content.webp`,
      happy: `${base}/check-ins/mood/mood-04-happy.webp`,
      excited: `${base}/check-ins/mood/mood-05-excited.webp`,
    },
    energy: {
      exhausted: `${base}/check-ins/energy/energy-01-exhausted.webp`,
      low: `${base}/check-ins/energy/energy-02-low.webp`,
      balanced: `${base}/check-ins/energy/energy-03-balanced.webp`,
      high: `${base}/check-ins/energy/energy-04-high.webp`,
      energized: `${base}/check-ins/energy/energy-05-energized.webp`,
    },
  },
  tabs: {
    work: `${base}/tab-icons/tab-work-briefcase.webp`,
    finance: `${base}/tab-icons/tab-finance-peso.webp`,
    health: `${base}/tab-icons/tab-health-leaf.webp`,
    love: `${base}/tab-icons/tab-love-heart.webp`,
  },
  mood: {
    calm: `${base}/mood-energy/mood_calm.webp`,
    sad: `${base}/mood-energy/mood_sad.webp`,
    overwhelmed: `${base}/mood-energy/mood_overwhelmed.webp`,
    loved: `${base}/mood-energy/mood_loved.webp`,
  },
  energy: {
    tired: `${base}/mood-energy/energy_tired.webp`,
    resting: `${base}/mood-energy/energy_resting.webp`,
    motivated: `${base}/mood-energy/energy_motivated.webp`,
  },
  weather: {
    partlySunny: `${base}/weather/weather_partly_sunny.webp`,
    cloudy: `${base}/weather/weather_cloudy.webp`,
    overcast: `${base}/weather/weather_overcast.webp`,
    rain: `${base}/weather/weather_rain.webp`,
    thunderstorm: `${base}/weather/weather_thunderstorm.webp`,
    windy: `${base}/weather/weather_windy.webp`,
    rainbow: `${base}/weather/weather_rainbow.webp`,
    snow: `${base}/weather/weather_snow.webp`,
    fog: `${base}/weather/weather_fog.webp`,
    tornado: `${base}/weather/weather_tornado.webp`,
  },
  time: {
    dawn: `${base}/time/time_dawn_peeking_sun.webp`,
    sunrise: `${base}/time/time_sunrise_soft_hills.webp`,
    morning: `${base}/time/time_morning_clear_sky.webp`,
    midday: `${base}/time/time_midday_bright_sun.webp`,
    earlyEvening: `${base}/time/time_early_evening_sun.webp`,
    goldenHour: `${base}/time/time_golden_hour.webp`,
    sunset: `${base}/time/time_sunset_pink_sky.webp`,
    twilight: `${base}/time/time_twilight.webp`,
    night: `${base}/time/time_night_crescent_moon.webp`,
    deepNight: `${base}/time/time_deep_night_stars.webp`,
  },
  sky: {
    cloud: `${base}/sky/sky_cloud_fluffy.webp`,
    sun: `${base}/sky/sky_sun_smiling.webp`,
    moon: `${base}/sky/sky_moon_with_stars.webp`,
    sparkles: `${base}/sky/sky_sparkle_stars.webp`,
    rainbow: `${base}/sky/sky_rainbow_clouds.webp`,
    wind: `${base}/sky/sky_wind_swirl_pastel.webp`,
    shootingStar: `${base}/sky/sky_shooting_star_pastel.webp`,
    sunCloud: `${base}/sky/sky_sun_behind_cloud.webp`,
    sleepingCloudMoon: `${base}/sky/sky_sleeping_cloud_moon.webp`,
    stars: `${base}/sky/sky_star_cluster_pastel.webp`,
  },
  plants: {
    leafy: `${base}/plants/plant_leafy.webp`,
    fern: `${base}/plants/plant_fern.webp`,
    hangingVine: `${base}/plants/plant_hanging_vine.webp`,
    lavender: `${base}/plants/plant_lavender.webp`,
    peaceLily: `${base}/plants/plant_peace_lily.webp`,
    pinkFlowers: `${base}/plants/plant_pink_flowers.webp`,
    pinkBlossoms: `${base}/plants/plant_pink_blossoms_blush_pot.webp`,
    succulent: `${base}/plants/plant_succulent_cluster.webp`,
    tallDracaena: `${base}/plants/plant_tall_dracaena.webp`,
    tallLeaves: `${base}/plants/plant_tall_leaves.webp`,
    yellowBlossoms: `${base}/plants/plant_yellow_blossoms.webp`,
    yellowBlossomsCreamPot: `${base}/plants/plant_yellow_blossoms_cream_pot.webp`,
  },
  nature: {
    flowers: `${base}/nature/nature_flower_cluster_pastel.webp`,
    leaves: `${base}/nature/nature_leaf_pair.webp`,
    butterflies: `${base}/nature/nature_butterflies_pastel_pair.webp`,
    bee: `${base}/nature/nature_bee_sparkle.webp`,
    dandelion: `${base}/nature/nature_dandelion_wish.webp`,
    mushroom: `${base}/nature/nature_mushroom_red_spotted.webp`,
    dragonfly: `${base}/nature/nature_dragonfly_blue.webp`,
    flowerPot: `${base}/nature/nature_flower_pot_pastel.webp`,
    acorns: `${base}/nature/nature_acorns_pair.webp`,
    woodland: `${base}/nature/nature_rocks_log_flowers.webp`,
  },
  cozy: {
    tea: `${base}/cozy/tea_cup_saucer.webp`,
    coffee: `${base}/cozy/coffee_mug.webp`,
    books: `${base}/cozy/stacked_books.webp`,
    candle: `${base}/cozy/heart_jar_candle.webp`,
    window: `${base}/cozy/cozy_window.webp`,
    blanket: `${base}/cozy/folded_blanket.webp`,
    pillow: `${base}/cozy/cat_pillow.webp`,
    wateringCan: `${base}/cozy/watering_can.webp`,
    rug: `${base}/cozy/round_woven_rug.webp`,
  },
  celebrations: {
    newYearFireworks: `${base}/celebrations/new_year_fireworks.webp`,
    newYearStars: `${base}/celebrations/new_year_star_cluster.webp`,
    newYearBanner: `${base}/celebrations/new_year_banner.webp`,
    valentinesHearts: `${base}/celebrations/valentines_heart_cluster.webp`,
    valentinesFlowers: `${base}/celebrations/valentines_flower_bouquet.webp`,
    valentinesLetter: `${base}/celebrations/valentines_love_letter.webp`,
    halloweenPumpkin: `${base}/celebrations/halloween_friendly_pumpkin.webp`,
    halloweenMoon: `${base}/celebrations/halloween_crescent_moon.webp`,
    halloweenGhost: `${base}/celebrations/halloween_friendly_ghost.webp`,
    easterEgg: `${base}/celebrations/easter_decorated_egg.webp`,
  },
} as const;

export type StillAssetPath = string;
