import { ArrowLeft, Bell, BriefcaseBusiness, CalendarDays, ChevronRight, CircleAlert, Clock3, Plus, StickyNote, Wrench } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import type { WorkNote, WorkProfile } from '../../domain/work';
import { useAppStore } from '../../stores/useAppStore';

type QueueStatus = 'todo' | 'progress' | 'done';
type IncidentStatus = 'new' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
type WorkIncident = { id: string; reference: string; title: string; priority: 'P1' | 'P2' | 'P3' | 'P4'; system?: string; status: IncidentStatus; note?: string; createdAt: number; updatedAt: number };
type ExtendedWorkProfile = WorkProfile & { incidents?: WorkIncident[]; workTaskStates?: Record<string, QueueStatus> };
type QueueItem = { id: string; kind: 'task' | 'meeting' | 'incident' | 'change' | 'reminder'; title: string; meta: string; status: QueueStatus; sort: string };

function key(date = new Date()) { return date.toISOString().slice(0, 10); }
function id(prefix: string) { return typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function shortDate(value?: string) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : ''; }

export function WorkQueuePage() {
  const navigate = useNavigate();
  const profile = useAppStore((state) => state.workProfile) as ExtendedWorkProfile;
  const tasks = useAppStore((state) => state.tasks);
  const events = useAppStore((state) => state.events);
  const updateProfile = useAppStore((state) => state.updateWorkProfile);
  const addTask = useAppStore((state) => state.addTask);
  const toggleTask = useAppStore((state) => state.toggleTask);
  const openEventEditor = useAppStore((state) => state.openEventEditor);
  const [tab, setTab] = useState<QueueStatus>('todo');
  const [taskTitle, setTaskTitle] = useState('');
  const [incidentOpen, setIncidentOpen] = useState(false);
  const [incident, setIncident] = useState({ reference: '', title: '', priority: 'P3' as WorkIncident['priority'], system: '' });
  const [noteOpen, setNoteOpen] = useState(false);
  const [noteText, setNoteText] = useState('');
  const [noteReminder, setNoteReminder] = useState('');
  const today = key();
  const incidents = profile.incidents ?? [];
  const taskStates = profile.workTaskStates ?? {};
  const notes = profile.notes ?? [];
  const changes = profile.changes ?? [];
  const saveProfile = (patch: Partial<ExtendedWorkProfile>) => updateProfile({ ...profile, ...patch } as WorkProfile);
  const workTasks = tasks.filter((task) => task.areaId === 'work');
  const todayMeetings = events.filter((event) => (event.areaId === 'work' || event.category === 'work') && event.startDate === today);
  const openIncidents = incidents.filter((item) => item.status !== 'closed' && item.status !== 'resolved');
  const openChanges = changes.filter((item) => item.status !== 'completed' && item.status !== 'cancelled');
  const activeReminders = notes.filter((note) => note.reminderDate && note.reminderDate >= today);

  const queue = useMemo<QueueItem[]>(() => {
    const items: QueueItem[] = [];
    workTasks.forEach((task) => items.push({ id: `task:${task.id}`, kind: 'task', title: task.title, meta: task.dueDate ? shortDate(task.dueDate) : 'Task', status: task.completed ? 'done' : (taskStates[task.id] ?? 'todo'), sort: task.dueDate ?? '9999' }));
    todayMeetings.forEach((event) => {
      const nowTime = new Date().toTimeString().slice(0, 5);
      const status: QueueStatus = event.startTime && event.startTime < nowTime ? 'done' : 'todo';
      items.push({ id: `meeting:${event.id}`, kind: 'meeting', title: event.title, meta: event.allDay ? 'All day · Meeting' : `${event.startTime ?? ''} · Meeting`, status, sort: event.startTime ?? '00:00' });
    });
    incidents.forEach((item) => items.push({ id: `incident:${item.id}`, kind: 'incident', title: `${item.reference ? `${item.reference} · ` : ''}${item.title}`, meta: `${item.priority}${item.system ? ` · ${item.system}` : ''} · Incident`, status: item.status === 'resolved' || item.status === 'closed' ? 'done' : item.status === 'in_progress' || item.status === 'waiting' ? 'progress' : 'todo', sort: String(item.createdAt) }));
    changes.forEach((change) => items.push({ id: `change:${change.id}`, kind: 'change', title: `${change.reference ? `${change.reference} · ` : ''}${change.title}`, meta: `${change.plannedDate ? `${shortDate(change.plannedDate)} · ` : ''}Change`, status: change.status === 'completed' || change.status === 'cancelled' ? 'done' : change.status === 'in_progress' || change.status === 'testing' ? 'progress' : 'todo', sort: change.plannedDate ?? '9999' }));
    notes.filter((note) => note.reminderDate && note.reminderDate <= today).forEach((note) => items.push({ id: `reminder:${note.id}`, kind: 'reminder', title: note.text, meta: `Reminder · ${shortDate(note.reminderDate)}`, status: 'todo', sort: note.reminderDate ?? today }));
    return items.sort((a, b) => a.sort.localeCompare(b.sort));
  }, [workTasks, todayMeetings, incidents, changes, notes, taskStates, today]);

  const visible = queue.filter((item) => item.status === tab);
  const counts = { todo: queue.filter((item) => item.status === 'todo').length, progress: queue.filter((item) => item.status === 'progress').length, done: queue.filter((item) => item.status === 'done').length };
  const addWorkTask = (event: FormEvent) => { event.preventDefault(); const title = taskTitle.trim(); if (!title) return; addTask({ title, priority: 'medium', repeat: 'none', areaId: 'work', dueDate: today }); setTaskTitle(''); };
  const advanceTask = (taskId: string) => { const current = taskStates[taskId] ?? 'todo'; if (current === 'todo') saveProfile({ workTaskStates: { ...taskStates, [taskId]: 'progress' } }); else if (current === 'progress') toggleTask(taskId); };
  const saveIncident = (event: FormEvent) => { event.preventDefault(); if (!incident.title.trim()) return; const now = Date.now(); saveProfile({ incidents: [{ id: id('incident'), reference: incident.reference.trim(), title: incident.title.trim(), priority: incident.priority, system: incident.system.trim() || undefined, status: 'new', createdAt: now, updatedAt: now }, ...incidents] }); setIncident({ reference: '', title: '', priority: 'P3', system: '' }); setIncidentOpen(false); };
  const advanceIncident = (item: WorkIncident) => { const status: IncidentStatus = item.status === 'new' ? 'in_progress' : item.status === 'in_progress' || item.status === 'waiting' ? 'resolved' : item.status; saveProfile({ incidents: incidents.map((entry) => entry.id === item.id ? { ...entry, status, updatedAt: Date.now() } : entry) }); };
  const saveNote = (event: FormEvent) => { event.preventDefault(); if (!noteText.trim()) return; const note: WorkNote = { id: id('work-note'), text: noteText.trim(), kind: 'note', createdAt: Date.now(), reminderDate: noteReminder || undefined }; saveProfile({ notes: [note, ...notes] }); setNoteText(''); setNoteReminder(''); setNoteOpen(false); };
  const icon = (kind: QueueItem['kind']) => kind === 'meeting' ? <CalendarDays size={15} /> : kind === 'incident' ? <CircleAlert size={15} /> : kind === 'change' ? <Wrench size={15} /> : kind === 'reminder' ? <Bell size={15} /> : <Clock3 size={15} />;

  return <main className="shell work-queue-page work-queue-refined">
    <style>{`
      .work-queue-refined{max-width:760px;padding-bottom:132px;color:var(--text-strong);--wq-accent:#725eaa;--wq-border:rgba(93,78,119,.10);--wq-muted:#817a8c;--wq-surface:rgba(255,255,255,.72)}
      .work-queue-refined button{font:inherit;color:inherit}.wq-head{display:flex;align-items:center;gap:13px;margin:10px 0 18px}.wq-back{width:42px;height:42px;border:1px solid var(--wq-border);border-radius:15px;background:rgba(255,255,255,.64);display:grid;place-items:center}.wq-head-copy{flex:1}.wq-kicker{margin:0 0 3px;color:#817692;font-size:.67rem;font-weight:850;letter-spacing:.16em;text-transform:uppercase}.wq-head h1{margin:0;font-family:var(--font-display);font-size:2.35rem;line-height:.95}.wq-subtitle{margin:7px 0 0;color:var(--wq-muted);font-size:.87rem}
      .wq-overview{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:24px}.wq-overview article{min-height:78px;padding:13px 14px;border:1px solid var(--wq-border);border-radius:20px;background:rgba(255,255,255,.58);box-shadow:none}.wq-overview small,.wq-overview strong{display:block}.wq-overview small{font-size:.66rem;color:var(--wq-muted);font-weight:750}.wq-overview strong{margin-top:6px;font-size:1.25rem;letter-spacing:-.03em}.wq-overview span{display:block;margin-top:2px;font-size:.67rem;color:var(--wq-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .wq-board{padding:16px 16px 14px;margin-bottom:28px;border:1px solid var(--wq-border);border-radius:24px;background:var(--wq-surface);box-shadow:0 12px 32px rgba(75,55,102,.045)}.wq-board-top{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.wq-board-top strong{font-size:1.02rem}.wq-board-top span{font-size:.72rem;color:var(--wq-muted)}.wq-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;padding:4px;margin:14px 0 10px;border-radius:14px;background:rgba(113,94,168,.07)}.wq-tabs button{border:0;background:transparent;padding:9px 4px;border-radius:11px;color:#7d7488;font-size:.72rem;font-weight:800}.wq-tabs button.active{background:rgba(255,255,255,.86);color:var(--wq-accent);box-shadow:0 1px 5px rgba(66,48,91,.07)}.wq-list{border-top:1px solid var(--wq-border)}.wq-row{width:100%;min-height:52px;display:flex;align-items:center;gap:10px;text-align:left;border:0;border-bottom:1px solid var(--wq-border);padding:9px 2px;background:transparent}.wq-row:last-child{border-bottom:0}.wq-row>span:first-child{width:30px;height:30px;flex:0 0 30px;border-radius:9px;background:rgba(113,94,168,.08);color:var(--wq-accent);display:grid;place-items:center}.wq-row div{flex:1;min-width:0}.wq-row strong,.wq-row small{display:block}.wq-row strong{font-size:.84rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.wq-row small{margin-top:2px;color:var(--wq-muted);font-size:.68rem}.wq-row>svg{color:#a29aaa}.wq-empty{padding:20px 8px;color:var(--wq-muted);text-align:center;font-size:.8rem}.wq-add{display:grid;grid-template-columns:1fr 40px;gap:7px;margin-top:10px}.wq-add input{min-width:0;min-height:40px;border:1px solid var(--wq-border);background:rgba(255,255,255,.62);border-radius:12px;padding:0 12px;color:inherit;font-size:.8rem}.wq-add button{border:0;border-radius:12px;background:rgba(113,94,168,.12);color:var(--wq-accent);display:grid;place-items:center}
      .wq-section{margin-top:27px}.wq-section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:9px}.wq-section-head h2{margin:0;font-family:var(--font-display);font-size:1.42rem;letter-spacing:-.02em}.wq-section-head button{min-height:34px;border:0;border-radius:11px;padding:0 10px;background:rgba(113,94,168,.08);color:var(--wq-accent);font-size:.72rem;font-weight:850;display:flex;align-items:center;gap:4px}.wq-card-list{overflow:hidden;border:1px solid var(--wq-border);border-radius:20px;background:rgba(255,255,255,.60)}.wq-record{width:100%;min-height:62px;padding:11px 14px;display:flex;gap:10px;align-items:center;border:0;border-bottom:1px solid var(--wq-border);background:transparent;text-align:left}.wq-record:last-child{border-bottom:0}.wq-record>svg:first-child{color:var(--wq-accent)}.wq-record>div{flex:1;min-width:0}.wq-record strong,.wq-record small{display:block}.wq-record strong{font-size:.81rem}.wq-record small{color:var(--wq-muted);margin-top:3px;font-size:.67rem}.wq-record>svg:last-child{color:#a59eab}.wq-card-list>.wq-empty{min-height:66px;display:grid;place-items:center;padding:10px}.wq-form{display:grid;gap:8px;padding:13px;margin-bottom:9px;border:1px solid var(--wq-border);border-radius:18px;background:rgba(255,255,255,.74)}.wq-form input,.wq-form select,.wq-form textarea{width:100%;box-sizing:border-box;min-height:42px;border:1px solid var(--wq-border);background:rgba(255,255,255,.68);border-radius:12px;padding:10px 11px;color:inherit;font-size:.79rem}.wq-form textarea{min-height:78px;resize:vertical}.wq-form-grid{display:grid;grid-template-columns:1fr 105px;gap:7px}.wq-form button{min-height:40px;border:0;border-radius:12px;background:rgba(113,94,168,.14);color:var(--wq-accent);font-weight:850}.wq-note-text{white-space:pre-wrap}.wq-footer-link{margin-top:30px;width:100%;padding:14px 15px;display:flex;align-items:center;gap:11px;border:1px solid var(--wq-border);border-radius:19px;background:rgba(255,255,255,.56);text-align:left}.wq-footer-link>svg:first-child{color:var(--wq-accent)}.wq-footer-link div{flex:1}.wq-footer-link strong{display:block;font-size:.85rem}.wq-footer-link span{display:block;color:var(--wq-muted);font-size:.68rem;margin-top:2px}.wq-footer-link>svg:last-child{color:#a59eab}
      @media(max-width:620px){.work-queue-refined{padding-left:18px;padding-right:18px}.wq-head{margin-top:5px}.wq-overview{grid-template-columns:repeat(2,1fr);gap:7px;margin-bottom:20px}.wq-overview article{min-height:70px;padding:11px 12px;border-radius:18px}.wq-board{padding:14px;border-radius:22px}.wq-section{margin-top:24px}.wq-section-head h2{font-size:1.3rem}}
    `}</style>

    <header className="wq-head"><button className="wq-back" onClick={() => navigate('/')} type="button" aria-label="Back home"><ArrowLeft size={18}/></button><div className="wq-head-copy"><p className="wq-kicker">Life area</p><h1>Work</h1><p className="wq-subtitle">{profile.jobTitle || profile.employer ? [profile.jobTitle, profile.employer].filter(Boolean).join(' · ') : 'Your workday at a glance.'}</p></div></header>

    <section className="wq-overview" aria-label="Work summary">
      <article><small>Meetings today</small><strong>{todayMeetings.length}</strong><span>{todayMeetings[0]?.startTime ? `Next ${todayMeetings[0].startTime}` : todayMeetings.length ? 'On your calendar' : 'Calendar is clear'}</span></article>
      <article><small>Incidents</small><strong>{openIncidents.length}</strong><span>{openIncidents[0]?.reference || 'Nothing open'}</span></article>
      <article><small>Changes</small><strong>{openChanges.length}</strong><span>{openChanges[0]?.reference || 'Nothing open'}</span></article>
      <article><small>Reminders</small><strong>{activeReminders.length}</strong><span>{activeReminders[0]?.reminderDate ? `Next ${shortDate(activeReminders[0].reminderDate)}` : 'Nothing waiting'}</span></article>
    </section>

    <section className="wq-board"><div className="wq-board-top"><strong>My work</strong><span>{counts.todo + counts.progress} active</span></div><div className="wq-tabs" role="tablist"><button className={tab==='todo'?'active':''} onClick={()=>setTab('todo')} type="button">To do · {counts.todo}</button><button className={tab==='progress'?'active':''} onClick={()=>setTab('progress')} type="button">In progress · {counts.progress}</button><button className={tab==='done'?'active':''} onClick={()=>setTab('done')} type="button">Done · {counts.done}</button></div><div className="wq-list">{visible.length===0?<div className="wq-empty">Nothing here right now.</div>:visible.map(item=><button className="wq-row" key={item.id} onClick={()=>{if(item.kind==='task')advanceTask(item.id.slice(5)); if(item.kind==='meeting')openEventEditor(item.id.slice(8)); if(item.kind==='incident'){const found=incidents.find(x=>x.id===item.id.slice(9));if(found)advanceIncident(found)} if(item.kind==='change')navigate('/work/details');}} type="button"><span>{icon(item.kind)}</span><div><strong>{item.title}</strong><small>{item.meta}</small></div><ChevronRight size={14}/></button>)}</div>{tab==='todo'&&<form className="wq-add" onSubmit={addWorkTask}><input aria-label="New work task" placeholder="Add a task" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/><button type="submit" aria-label="Add task"><Plus size={16}/></button></form>}</section>

    <section className="wq-section"><div className="wq-section-head"><h2>Incidents</h2><button onClick={()=>setIncidentOpen(v=>!v)} type="button"><Plus size={14}/>Incident</button></div>{incidentOpen&&<form className="wq-form" onSubmit={saveIncident}><div className="wq-form-grid"><input placeholder="INC number" value={incident.reference} onChange={e=>setIncident(v=>({...v,reference:e.target.value}))}/><select value={incident.priority} onChange={e=>setIncident(v=>({...v,priority:e.target.value as WorkIncident['priority']}))}><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></div><input required placeholder="What happened?" value={incident.title} onChange={e=>setIncident(v=>({...v,title:e.target.value}))}/><input placeholder="System / SID" value={incident.system} onChange={e=>setIncident(v=>({...v,system:e.target.value}))}/><button type="submit">Add incident</button></form>}<div className="wq-card-list">{openIncidents.length===0?<div className="wq-empty">No open incidents.</div>:openIncidents.map(item=><button className="wq-record" key={item.id} onClick={()=>advanceIncident(item)} type="button"><CircleAlert size={16}/><div><strong>{item.reference ? `${item.reference} · ` : ''}{item.title}</strong><small>{item.priority}{item.system?` · ${item.system}`:''} · {item.status.replace('_',' ')}</small></div><ChevronRight size={14}/></button>)}</div></section>

    <section className="wq-section"><div className="wq-section-head"><h2>Changes</h2><button onClick={()=>navigate('/work/details')} type="button"><Plus size={14}/>Change</button></div><div className="wq-card-list">{openChanges.length===0?<div className="wq-empty">No open changes.</div>:openChanges.slice(0,5).map(change=><button className="wq-record" key={change.id} onClick={()=>navigate('/work/details')} type="button"><Wrench size={16}/><div><strong>{change.reference ? `${change.reference} · ` : ''}{change.title}</strong><small>{[change.system, change.plannedDate ? shortDate(change.plannedDate) : undefined, change.status.replace('_',' ')].filter(Boolean).join(' · ')}</small></div><ChevronRight size={14}/></button>)}</div></section>

    <section className="wq-section"><div className="wq-section-head"><h2>Notes</h2><button onClick={()=>setNoteOpen(v=>!v)} type="button"><Plus size={14}/>Note</button></div>{noteOpen&&<form className="wq-form" onSubmit={saveNote}><textarea required placeholder="Jot something down…" value={noteText} onChange={e=>setNoteText(e.target.value)}/><input type="date" aria-label="Reminder date" value={noteReminder} onChange={e=>setNoteReminder(e.target.value)}/><button type="submit">Save note</button></form>}<div className="wq-card-list">{notes.length===0?<div className="wq-empty">No notes yet.</div>:notes.slice(0,6).map(note=><div className="wq-record" key={note.id}><StickyNote size={16}/><div><strong className="wq-note-text">{note.text}</strong><small>{note.reminderDate?`Reminder · ${shortDate(note.reminderDate)}`:'Note'}</small></div>{note.reminderDate?<Bell size={14}/>:null}</div>)}</div></section>

    <button className="wq-footer-link" onClick={()=>navigate('/work/details')} type="button"><BriefcaseBusiness size={18}/><div><strong>Time, pay & workplace</strong><span>Shifts, PTO, schedule, pay and settings</span></div><ChevronRight size={15}/></button>
  </main>;
}
